# lightning.pytorch==2.1.3
data:
  AppliancesEnergy
model:
  n_block: 6
  ch_in: 24
  seq_len: 144
  hidden_size: 128
  activation: relu
  dropout: 0.2
  revin: True
  univariate: False
  gmlp_proj: False
  lr: 0.0005
  lr_patience: 50
early_stopping:
  monitor: val_mse
  patience: 200
