# lightning.pytorch==2.1.3
data:
  AppliancesEnergy
model:
  n_block: 4
  ch_in: 24
  seq_len: 144
  hidden_size: 2048
  activation: relu
  dropout: 0.5
  revin: True
  univariate: False
  gmlp_proj: True
  gmlp_blocks: 6
  gmlp_patch_size: 1
  gmlp_d_model: 256
  gmlp_d_ffn: 512
  lr: 0.0005
  lr_patience: 50
early_stopping:
  monitor: val_mse
  patience: 200
