# lightning.pytorch==2.1.3
data:
  AustraliaRainfall
model:
  n_block: 1
  ch_in: 3
  seq_len: 24
  hidden_size: 512
  activation: relu
  dropout: 0.2
  revin: True
  univariate: False
  gmlp_proj: False
  lr: 0.0005
  lr_patience: 10
early_stopping:
  monitor: val_mse
  patience: 50
