# lightning.pytorch==2.1.3
data:
  AustraliaRainfall
model:
  n_block: 2
  ch_in: 3
  seq_len: 24
  hidden_size: 256
  activation: relu
  dropout: 0.2
  revin: True
  univariate: False
  gmlp_proj: True
  gmlp_blocks: 6
  gmlp_patch_size: 1
  gmlp_d_model: 256
  gmlp_d_ffn: 256
  lr: 0.0005
  lr_patience: 10
early_stopping:
  monitor: val_mse
  patience: 50