 # lightning.pytorch==2.1.3
data:
  BeijingPM10Quality
model:
  n_block: 4
  ch_in: 9
  seq_len: 24
  hidden_size: 128
  activation: relu
  dropout: 0.2
  revin: True
  univariate: False
  gmlp_proj: True
  gmlp_blocks: 4
  gmlp_patch_size: 1
  gmlp_d_model: 256
  gmlp_d_ffn: 512
  lr: 0.0005
  lr_patience: 10
early_stopping:
  monitor: val_mse
  patience: 50