# lightning.pytorch==2.1.3
data:
  BeijingPM10Quality
model:
  n_block: 2
  ch_in: 9
  seq_len: 24
  hidden_size: 256
  activation: relu
  dropout: 0.2
  revin: True
  univariate: False
  gmlp_proj: False
  lr: 0.0005
  lr_patience: 10
early_stopping:
  monitor: val_mse
  patience: 50