# lightning.pytorch==2.1.3
data:
  BenzeneConcentration
model:
  n_block: 1
  ch_in: 8
  seq_len: 240
  hidden_size: 128
  activation: relu
  dropout: 0.5
  revin: True
  univariate: False
  gmlp_proj: True
  gmlp_blocks: 6
  gmlp_patch_size: 1
  gmlp_d_model: 256
  gmlp_d_ffn: 256
  lr: 0.0005
  lr_patience: 10
early_stopping:
  monitor: val_mse
  patience: 50