# lightning.pytorch==2.1.3
data:
  BIDMC32RR
model:
  n_block: 4
  ch_in: 2
  seq_len: 4000
  hidden_size: 256
  activation: relu
  dropout: 0.33
  revin: True
  univariate: False
  gmlp_proj: True
  gmlp_blocks: 4
  gmlp_patch_size: 1
  gmlp_d_model: 256
  gmlp_d_ffn: 256
  lr: 0.0005
  lr_patience: 5
early_stopping:
  monitor: val_mse
  patience: 20


