# lightning.pytorch==2.1.3
data:
  BIDMC32HR
model:
  n_block: 1
  ch_in: 2
  seq_len: 4000
  hidden_size: 256
  activation: relu
  dropout: 0.33
  revin: False
  univariate: False
  gmlp_proj: False
  lr: 0.0005
  lr_patience: 20
early_stopping:
  monitor: val_mse
  patience: 80
