# lightning.pytorch==2.1.3
data:
  Covid3Month
model:
  n_block: 1
  ch_in: 1
  seq_len: 84
  hidden_size: 512
  activation: relu
  dropout: 0.9
  revin: True
  univariate: False
  gmlp_proj: True
  gmlp_blocks: 1
  gmlp_patch_size: 1
  gmlp_d_model: 256
  gmlp_d_ffn: 256
  lr: 0.0005
  lr_patience: 100
early_stopping:
  monitor: val_mse
  patience: 400