# lightning.pytorch==2.1.3
data:
  Covid3Month
model:
  n_block: 4
  ch_in: 1
  seq_len: 84
  hidden_size: 256
  activation: relu
  dropout: 0.5
  revin: True
  univariate: False
  lr: 0.0005
  lr_patience: 100
early_stopping:
  monitor: val_mse
  patience: 400