# lightning.pytorch==2.1.3
data:
  FloodModeling2
model:
  n_block: 6
  ch_in: 1
  seq_len: 266
  hidden_size: 128
  activation: relu
  dropout: 0.2
  revin: True
  univariate: True
  gmlp_proj: False
  lr: 0.0005
  lr_patience: 100
early_stopping:
  monitor: val_mse
  patience: 400