# lightning.pytorch==2.1.3
data:
  HouseholdPowerConsumption1
model:
  n_block: 1
  ch_in: 5
  seq_len: 1440
  hidden_size: 1024
  activation: relu
  dropout: 0.2
  revin: False
  univariate: False
  gmlp_proj: False
  lr: 0.0005
  lr_patience: 20
early_stopping:
  monitor: val_mse
  patience: 80
