# lightning.pytorch==2.1.3
data:
  HouseholdPowerConsumption1
model:
  n_block: 1
  ch_in: 5
  seq_len: 1440
  hidden_size: 1024
  activation: relu
  dropout: 0.2
  revin: True
  univariate: False
  gmlp_proj: True
  gmlp_blocks: 2
  gmlp_patch_size: 1
  gmlp_d_model: 256
  gmlp_d_ffn: 512
  lr: 0.0005
  lr_patience: 10
early_stopping:
  monitor: val_mse
  patience: 40