# lightning.pytorch==2.1.3
data:
  IEEEPPG
model:
  n_block: 2
  ch_in: 5
  seq_len: 1000
  hidden_size: 128
  activation: relu
  dropout: 0.5
  revin: True
  univariate: False
  gmlp_proj: False
  lr: 0.0005
  lr_patience: 10
early_stopping:
  monitor: val_mse
  patience: 40
