# lightning.pytorch==2.1.3
data:
  LiveFuelMoistureContent
model:
  n_block: 1
  ch_in: 7
  seq_len: 365
  hidden_size: 128
  activation: relu
  dropout: 0.5
  revin: True
  univariate: False
  gmlp_proj: False
  lr: 0.0005
  lr_patience: 10
early_stopping:
  monitor: val_mse
  patience: 40
