# lightning.pytorch==2.1.3
data:
  NewsTitleSentiment
model:
  n_block: 6
  ch_in: 3
  seq_len: 144
  hidden_size: 256
  activation: relu
  dropout: 0.5
  revin: True
  univariate: False
  gmlp_proj: False
  lr: 0.0005
  lr_patience: 5
early_stopping:
  monitor: val_mse
  patience: 20