# lightning.pytorch==2.1.3
data:
  PPGDalia
model:
  n_block: 4
  ch_in: 4
  seq_len: 512
  hidden_size: 128
  activation: relu
  dropout: 0.2
  revin: True
  univariate: False
  gmlp_proj: False
  lr: 0.0005
  lr_patience: 10
early_stopping:
  monitor: val_mse
  patience: 40
